# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='user_ID',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='user_ID',
            new_name='username',
        ),
    ]
