# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20161108_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='content',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='component',
            name='content_file',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='component',
            name='content_type',
            field=models.CharField(choices=[('1', 'File'), ('2', 'Text'), ('3', 'Image')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='component',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.Module'),
        ),
    ]
