# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20161108_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='content',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='content_file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
