# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20161109_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='localPosition',
            field=models.IntegerField(default=0),
        ),
    ]
